#!/usr/bin/env bash
#
# check-required-docs.sh — the documents this repository's code points at exist,
# and still carry the sections it points at.
#
# Issue #121, ported from the js template's scripts/check-required-docs.sh
# (hive-mind principle #12, "documentation validation"). The template asserts
# that a fixed list of documents exists and carries a fixed list of `## `
# headings; this repository has a concrete reason for each entry, so the table
# below records the consumer next to every rule it protects.
#
# WHY A HEADING IS A CONTRACT HERE
#   scripts/update-readme-sizes.sh inserts the generated component-sizes section
#   *before* `## License`, falling back to `## Documentation` — and
#   measure-disk-space.yml commits the result to main. Rename either heading and
#   the section is appended to the end of the file instead, with the job green.
#   scripts/release/preflight-credentials.sh sends an operator holding a rejected
#   credential to "the 'Releasing' section of README.md". Rename that heading and
#   the instruction points at nothing, on the one day somebody needs it.
#   Neither failure produces an annotation anywhere, which is what makes them
#   the same class as everything else in issue #121: nothing looks, so nothing
#   reports.
#
#   lychee (links.yml) is the other half of this and does not overlap with it:
#   it reads markdown links and now their fragments, so it sees a link that
#   points at a missing file or a missing anchor. It never sees a document that
#   no page links to, and it never reads a shell script or a workflow.
#
# WHAT IT CHECKS
#   1. Every document in REQUIREMENTS below exists, is tracked, and is not
#      empty.
#   2. Every `## ` section listed for it is present, spelled exactly.
#   3. README.md carries the two component-size markers, once each and in
#      order; measure-disk-space.yml greps between them and
#      update-readme-sizes.sh rewrites what is between them.
#   4. Every `docs/...` path named in scripts/ and .github/ — in prose, in a
#      comment, or inside an error message a human is expected to follow —
#      resolves to a file that exists.
#
# WHAT IT DOES NOT FLAG
#   The contents of a section: this asserts that the heading a consumer depends
#   on is there, not that anything true is written under it.
#
#   Rule 4 reads `docs/...` paths and nothing else, which is a deliberate
#   boundary rather than an oversight. A bare `CHANGELOG.md` in a comment may be
#   an example, another project's file, or a file relative to a directory the
#   comment names two lines earlier, and firing on all three would make this
#   gate the kind of false positive issue #121 is about — measured: the bare-name
#   form flagged two of this script's own sentences. Any other directory prefix
#   has the same problem for a different reason: `lychee/out.md` is an artifact
#   links.yml creates at run time, and `$REPO_ROOT/README.md` is a path with a
#   variable in it. A `docs/...` path is a claim about this repository's layout,
#   and is checked as one.
#
#   URLs are stripped before rule 4 runs, so another project's document named in
#   a link is not resolved against this tree; links.yml checks those.
#
# USAGE
#   scripts/ci/check-required-docs.sh [--list] [--list-inputs] [--verbose]
#
#   --list    print the table as `path<TAB>section` lines and exit; the fixtures
#             build their trees from this rather than from a second copy of it.
#   --verbose (default off) name every document and every mention as it is
#             checked.
#
#   No positional file arguments: the requirement table *is* the input, and rule
#   4 discovers its scope with `git ls-files`, so the check reports on the tree
#   rather than on a caller's list.
#
# EXIT
#   0 = every document, section, marker and mention is in place
#   1 = at least one is not
#   2 = the check could not run (not a git repository, bad usage)

set -euo pipefail

# path|section|section|...
#
# A section is listed when something outside the document depends on that exact
# spelling, or when it is the entry point the README's own navigation promises.
REQUIREMENTS=(
  # `## Component Sizes` is generated by scripts/update-readme-sizes.sh;
  # `## License` and `## Documentation` are the anchors it inserts before;
  # `## Releasing` is where scripts/release/preflight-credentials.sh sends an
  # operator whose credential was rejected; the rest is the navigation the
  # README's own Documentation section promises a reader.
  "README.md|Overview|Docker Images|Usage|Component Sizes|Releasing|Documentation|License"
  # Linked from README's `## Documentation`, and the two documents the
  # repository's own contributing instructions send a reader to first.
  "ARCHITECTURE.md|Overview|System Architecture|Build Pipeline|File Structure|Design Decisions"
  "REQUIREMENTS.md|Functional Requirements|Non-Functional Requirements|CI/CD Requirements"
  # Named by scripts/release/check-publication.sh and
  # scripts/release/docker-push-failure-classifier.sh in the errors they print
  # when a release cannot publish; those messages are useless if the sections
  # they promise are gone.
  "docs/RELEASING.md|What a release needs|Making the GHCR packages public|Checking a release by hand"
  # Named by scripts/ci/run-with-budget-warning.sh and by every workflow that
  # carries a budget comment.
  "docs/CI-TIMEOUT-BUDGETS.md|The rule|Current budgets|Re-measuring"
  # The document the dind box's own --help and its sudoers contract point at.
  "docs/dind/USAGE.md|Runtime Flags|Sudoers Contract|Host Prerequisites"
)

# The markers measure-disk-space.yml greps for and update-readme-sizes.sh
# rewrites between.
MARKER_FILE="README.md"
MARKER_START="<!-- COMPONENT_SIZES_START -->"
MARKER_END="<!-- COMPONENT_SIZES_END -->"

VERBOSE=0
LIST=0
LIST_INPUTS=0

while [ $# -gt 0 ]; do
  case "$1" in
    --list)
      LIST=1
      shift
      ;;
    --list-inputs)
      LIST_INPUTS=1
      shift
      ;;
    --verbose)
      VERBOSE=1
      shift
      ;;
    -h | --help)
      sed -n '2,60p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "check-required-docs.sh: unknown argument $1" >&2
      exit 2
      ;;
  esac
done

# `git ls-files` answers about the current directory, not about the repository:
# run from a subdirectory it lists that subtree alone, and lists it with paths
# relative to that subdirectory. A gate that discovers its own inputs without
# anchoring first therefore sweeps a fraction of the tree and exits 0 over it,
# which reads exactly like a clean repository — and answers --list-inputs with
# paths no repository-root `paths:` pattern can match (issue #121). Anchor at
# the top of whichever repository the caller is standing in, not at this
# script's own location, so the fixtures can still drive it inside a throwaway
# repository.
if ! REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "check-required-docs.sh: not inside a git repository" >&2
  exit 2
fi
cd "$REPO_ROOT" || exit 2

# --list-inputs answers a different question from --list: not "what does this
# check require" but "which files does it read", one repository-relative path
# per line and nothing else. scripts/ci/check-workflow-path-coverage.mjs uses
# it to check that a change to any of them can start the workflow that runs
# this gate (issue #121). The mention scan walks scripts/ and .github/, so a
# script that names a document is an input as much as the document is: a .mjs
# file pointing at a document that is not there is exactly what rule 4 catches,
# and it can only catch it if editing that .mjs starts this workflow.
if [ "$LIST_INPUTS" -eq 1 ]; then
  {
    for entry in "${REQUIREMENTS[@]}"; do
      printf '%s\n' "${entry%%|*}"
    done
    printf '%s\n' "$MARKER_FILE"
    git ls-files -- scripts .github
  } | sort -u
  exit 0
fi

if [ "$LIST" -eq 1 ]; then
  for entry in "${REQUIREMENTS[@]}"; do
    path="${entry%%|*}"
    rest="${entry#"$path"}"
    if [ -z "$rest" ]; then
      printf '%s\n' "$path"
      continue
    fi
    IFS='|' read -r -a sections <<<"${rest#|}"
    for section in "${sections[@]}"; do
      printf '%s\t%s\n' "$path" "$section"
    done
  done
  exit 0
fi

findings=0
checked_docs=0
checked_sections=0
checked_mentions=0

annotate() {
  # $1 file, $2 line (may be empty), $3 title, $4 message
  local file="$1" line="$2" title="$3" message="$4"
  echo "::error file=${file}${line:+,line=$line},title=${title}::${message}"
  findings=$((findings + 1))
}

# --- Rules 1 and 2: the documents and the sections they promise ---------------
for entry in "${REQUIREMENTS[@]}"; do
  path="${entry%%|*}"
  rest="${entry#"$path"}"

  if [ ! -f "$path" ]; then
    annotate "$path" "" "Required document is missing" \
      "$path is required by the table in scripts/ci/check-required-docs.sh, which names the consumer of every entry. Restore it, or remove the entry with the consumer."
    continue
  fi

  if ! git ls-files --error-unmatch "$path" >/dev/null 2>&1; then
    annotate "$path" "" "Required document is untracked" \
      "$path exists in the working tree but is not tracked, so a fresh checkout — every CI job — does not have it."
    continue
  fi

  if [ ! -s "$path" ]; then
    annotate "$path" "" "Required document is empty" "$path is required but has no content."
    continue
  fi

  checked_docs=$((checked_docs + 1))
  [ "$VERBOSE" -eq 1 ] && echo "  [doc] $path"

  [ -n "$rest" ] || continue
  IFS='|' read -r -a sections <<<"${rest#|}"
  for section in "${sections[@]}"; do
    if grep -Fxq "## ${section}" "$path"; then
      checked_sections=$((checked_sections + 1))
      [ "$VERBOSE" -eq 1 ] && echo "  [section] $path :: ## $section"
      continue
    fi
    annotate "$path" "" "Required section is missing" \
      "$path no longer has a '## ${section}' heading. Something outside the document depends on that exact spelling — see the comment above its entry in scripts/ci/check-required-docs.sh."
  done
done

# --- Rule 3: the markers a workflow writes between -----------------------------
if [ -f "$MARKER_FILE" ]; then
  starts="$(grep -Fc "$MARKER_START" "$MARKER_FILE" || true)"
  ends="$(grep -Fc "$MARKER_END" "$MARKER_FILE" || true)"
  if [ "$starts" -ne 1 ] || [ "$ends" -ne 1 ]; then
    annotate "$MARKER_FILE" "" "Component-size markers are not a single pair" \
      "Found $starts start and $ends end marker(s); measure-disk-space.yml rewrites what is between exactly one pair, and anything else silently loses or duplicates the generated table."
  else
    start_line="$(grep -Fn "$MARKER_START" "$MARKER_FILE" | cut -d: -f1)"
    end_line="$(grep -Fn "$MARKER_END" "$MARKER_FILE" | cut -d: -f1)"
    if [ "$start_line" -ge "$end_line" ]; then
      annotate "$MARKER_FILE" "$start_line" "Component-size markers are out of order" \
        "The start marker is at line $start_line and the end marker at line $end_line."
    else
      [ "$VERBOSE" -eq 1 ] && echo "  [markers] $MARKER_FILE lines $start_line..$end_line"
    fi
  fi
fi

# --- Rule 4: the documents the code sends people to ---------------------------
#
# URLs are stripped first, so a best-practices document linked from another
# repository is not resolved against this tree.
#
# `|| true` on the grep: under `set -e` a file with no documentation mention in
# it — most of them — would end the inner loop at the first such file, and the
# check would silently report on a fraction of the tree. It scanned 3 mentions
# instead of 61 while that was missing, and said OK either way.
while IFS= read -r hit; do
  [ -n "$hit" ] || continue
  file="${hit%%:*}"
  rest="${hit#*:}"
  lineno="${rest%%:*}"
  mention="${rest#*:}"

  checked_mentions=$((checked_mentions + 1))

  if [ -f "$mention" ]; then
    [ "$VERBOSE" -eq 1 ] && echo "  [mention] $file:$lineno -> $mention"
    continue
  fi

  annotate "$file" "$lineno" "Documentation path does not exist" \
    "This line names $mention, and there is no such file. A reader following it — or an operator following the error message it is part of — lands nowhere."

done < <(
  git ls-files -- scripts .github | while IFS= read -r f; do
    [ -f "$f" ] || continue
    sed 's|https\?://[^ )"'"'"']*||g' "$f" \
      | grep -noE 'docs/[A-Za-z0-9._/-]+\.md' \
      | sed "s|^|$f:|" || true
  done
)

if [ "$findings" -gt 0 ]; then
  echo ""
  echo "check-required-docs.sh: $findings finding(s)."
  exit 1
fi

echo "check-required-docs.sh: OK — $checked_docs document(s), $checked_sections section(s), and $checked_mentions documentation mention(s) in scripts/ and .github/."
exit 0
